### PR TITLE
Add CHANGELOG

### LINKED ISSUE #382: Kermit changelog
Please publish changelog with each release. You not provided information about what changed in 2.x version comparing to 1.x. And further releases published without any information about changes.

### PR DESCRIPTION
**Pull request by findjigar**
Fixes #382

### CODE REVIEW

**Comment by findjigar** [comment]
> Why not provide this file to release action?
> 
> > bodyFile:	An optional body file for the release. This should be the path to the file.

I'm okay with manual effort for now. Will discuss automation later depending on how frequently we change features. We might also work on automatic release notes generation based on commit messages. For now, manual changelog is enough to satisfy the expectation of the community.

**Comment by dzmpr** [comment]
> For now, manual changelog is enough

You plan to copy changelog for every release? It's inconvenient to keep the changelog only in code. F.e. to check the changelog for older versions you need to find the corresponding commit in the repository , rather than just read it from the release post.

**Comment by dzmpr** [comment]
I don't see any ambiguity in the decision to publish the release notes. Generating them based on commits is a separate step that can be done later. But publishing notes from the file are the minimum for comfortable use of the library.
So far, no differences between versions 1.x.x and 2.x.x have been published anywhere. It is not clear to users what to expect from the new version and how to migrate to it. That's why we within the team are still using version 1.2.3.

**Comment by findjigar** [comment]
> I don't see any ambiguity in the decision to publish the release notes. Generating them based on commits is a separate step that can be done later. But publishing notes from the file are the minimum for comfortable use of the library. So far, no differences between versions 1.x.x and 2.x.x have been published anywhere. It is not clear to users what to expect from the new version and how to migrate to it. That's why we within the team are still using version 1.2.3.

Adding older changelog manually is not in scope for this PR. Also, not possible through release action, as older releases doesn't have accurate notes for all versions.

For now, you can go through our docs (https://kermit.touchlab.co/docs/) and Kermit samples to try out the newer version.

**Review by samhill303 — APPROVED** [review]

**Comment by dzmpr** [comment]
So, how much more time needed to add changelog?

**Pull request merged**
